/*
You are given a string stored in a variablestr, and the length of the string is stored in a variable with the nameN

The value stored inNwill always be even

You have to make two strings from the given string, such that the first string contains all the characters in the first half, and the second string contains all the characters present in the second half

For example, if the value stored inN = 6, andstr = "ababcb", then the string generated by the characters in the first half isaba, and the string generated by the characters in the second half isbcb. Since, both the strings are palindromes, the output isyes

Note : The string contains only lower case English Alphabets, and the length of the string will always be an even number

Input
The first line of the input contains the value stored inN

The next line of the input contains the value stored instr


Output
Printyesornobased on the conditions as mentioned in the problem statement

Sample Input 1 

6
ababcb
Sample Output 1

yes
Sample Input 2 

4
abdc
Sample Output 2

no
Sample Input 3 

6
ababba
Sample Output 3

no
*/

function halfPalindrome(N, str) {
  var first = str.slice(0, N/2);
  var second = str.slice(N/2, N);
  var farr = first.split('');
  farr = farr.reverse();
  var sarr = second.split('');
  sarr = sarr.reverse();
  if(farr.join('') == first && sarr.join('') == second) {
      console.log("yes");
  } else {
      console.log("no");
  }
}